package state;

// Import packages
import java.util.Scanner;
/**
 * @author Luke Howe
 */

 /**
  * This is the Arithemetic Game class. It handles the logic behind the game.
  */
public class ArithemeticGame {
    
    // Create instance variables
    private State easyState;
    private State mediumState;
    private State hardState;
    private State state;
    private int score;

    // Create constructor
    public ArithemeticGame() {
        easyState = new Easy(this);
        mediumState = new Medium(this);
        hardState = new Hard(this);
        state = easyState;
        this.score = 0;
        Scanner keyboard;

    }

    /**
     * This is the pressQuestionButton() method. It is what prints the question to the user and handles the user input and score.
     */
    public void pressQuestionButton() {
        int firstNumber = state.getNum();
        int secNumber = state.getNum();
        String opCode = state.getOperation();
        System.out.println(firstNumber+" "+opCode+" "+secNumber+" = ?");
        Scanner keyboard = new Scanner(System.in);
        int userInput = keyboard.nextInt();
        int answer = calculate(firstNumber, opCode, secNumber);
        if(userInput == answer) {
            System.out.println("Correct");
            score++;
        }
        if(userInput != answer) {
            System.out.println("Incorrect");
            score--;
        }
        if(score >= 3) {
            this.state.levelUp();
            score = 0;
        }
        if(score <= -3) {
            state.levelDown();
            score = 0;
        }
    }

    /**
     * This is the setState method. It changes the state of the game.
     * @param state This value holds the state that the game is being changed to.
     */
    public void setState(State state) {
        this.state = state;
    }

    /**
     * This is the getter for the Easy State.
     * @return This method returns the easyState variable for the Game.
     */
    public State getEasyState() {
        return easyState;
    }

    /**
     * This is the getter for the Medium State.
     * @return This method returns the mediumState variable for the Game.
     */
    public State getMediumState() {
        return mediumState;
    }

    /**
     * This is the getter for the Hard State.
     * @return This method returns the hardState variable for the Game.
     */
    public State getHardState() {
        return hardState;
    }

    /**
     * This is the calculate method. It is a helper method for the pressQuestionButton() method.
     * @param firstNum This value holds the first number generated by the state.
     * @param operation This value holds the operation that is generated by the state,
     * @param secNum This value holds the second number generated by the state.
     * @return This method returns the correct answer calculated from the first and second number and the operation.
     */
    public int calculate(int firstNum, String operation, int secNum) {
        if(operation == "+") {
            return firstNum + secNum;
        }
        else if(operation == "-") {
            return firstNum - secNum;
        }
        else if(operation == "*") {
            return firstNum * secNum;
        }
        return firstNum / secNum;
    }
}
